version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: pizzatime
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: veceloe/pizzatime:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "443:9090"
    depends_on:
      - postgres

volumes:
  postgres-data:
