server:
  port: 9090
spring:
  freemarker.suffix: .ftl
  jpa:
    hibernate:
      ddl-auto: create
  mail.default-encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: pizzatimegel@gmail.com
    password: twyaiknhtfjvknyn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://postgres/pizzatime
    username: postgres
    password: postgres
  thymeleaf:
    prefix: classpath:/templates/